name: Destroy Dev

on:
  workflow_dispatch:
    inputs:

env:
  REGISTRY: ghcr.io/jos1k/passwordpusher-api
  tf_actions_working_dir: infrastructure/dev

jobs:
  deploy_stp:
    name: Deploy
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: ${{ env.tf_actions_working_dir }}
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{secrets.AWS_AUTH_ROLE}}
          aws-region: ${{vars.AWS_REGION}}
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.1
      - name: Terraform Init
        id: init
        run: terraform init
        continue-on-error: true
      - name: Terraform Apply
        id: apply
        run: terraform destroy -auto-approve